# Generated by Django 4.2.5 on 2023-09-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publications',
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='django_app.category', verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
