# Generated by Django 4.2.6 on 2023-10-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
    ]
