# Generated by Django 4.2.5 on 2023-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Политика', 'Политика'), ('Экономика', 'Экономика'), ('Спорт', 'Спорт'), ('Наука и технологии', 'Наука и технологии'), ('Культура и искусство', 'Культура и искусство'), ('Здоровье и медицина', 'Здоровье и медицина'), ('Образование', 'Образование'), ('Природа', 'Природа'), ('Развлечения', 'Развлечения'), ('Туризм', 'Туризм')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
