# Generated by Django 4.2.5 on 2023-10-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Политика', 'Политика'), ('Экономика', 'Экономика'), ('Спорт', 'Спорт'), ('Наука и технологии', 'Наука и технологии'), ('Культура и искусство', 'Культура и искусство'), ('Здоровье и медицина', 'Здоровье и медицина'), ('Образование', 'Образование'), ('Природа', 'Природа'), ('Развлечения', 'Развлечения'), ('Туризм', 'Туризм')], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
