# Generated by Django 4.2.5 on 2023-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('teachers', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('nationality', models.TextField()),
                ('image', models.ImageField(upload_to='images/posts', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/posts', verbose_name='Изображение')),
            ],
        ),
    ]
