# Generated by Django 4.2.6 on 2023-10-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_photo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
    ]
