# Generated by Django 4.2.5 on 2023-11-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0008_postcomments_rating_delete_commentrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggests",
            name="status",
            field=models.CharField(
                choices=[("published", "Published"), ("unpublished", "Unpublished")],
                default="published",
                max_length=20,
            ),
        ),
    ]
