# Generated by Django 4.2.2 on 2023-06-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Опубликовать книгу',
            },
        ),
    ]
